ttoss/ttoss

docs/storybook/stories/landing-pages/Footer.stories.tsx
docs/storybook/stories/landing-pages/Navbar.stories.tsx
packages/landing-pages/package.json
packages/landing-pages/src/Footer/Footer.tsx
packages/landing-pages/src/Navbar/Navbar.tsx
packages/landing-pages/src/index.ts
packages/ui/src/components/Icon/Icon.tsx
yarn.lock

Task 341/criar componentes session bruttal rayza

---

packages/forms/src/FormField.tsx
packages/forms/src/index.ts
packages/forms/tests/FormFieldCheckbox.test.tsx
packages/forms/tests/FormFieldInput.test.tsx
packages/forms/tests/FormFieldRadio.test.tsx
packages/forms/tests/FormFieldSelect.test.tsx

fix: export all form fields

---

packages/ui/src/theme/ThemeProvider.tsx
packages/ui/tests/unit/ThemeProvider.test.tsx

Define default theme for @ttoss/UI

---

packages/react-auth/src/AuthProvider.tsx
packages/react-auth/src/index.ts
packages/react-auth/tests/unit/AuthProvider.test.tsx

fix: render nothing when is authenticated is undefined

---

packages/appsync-api/src/createApiTemplate.ts
packages/appsync-api/tests/apiTemplate.test.ts
packages/cloud-auth/src/template.ts
packages/cloud-auth/tests/unit/template.test.ts

feat: add iam auth to appsync-api

---

packages/appsync-api/src/createApiTemplate.ts
packages/appsync-api/tests/apiTemplate.test.ts

- Fixes #153 
- Add Lambda variables

feat: add environments to appsync api template

---

packages/appsync-api/src/createApiTemplate.ts
packages/appsync-api/tests/unit/apiTemplate.test.ts

fix: remove comments from sdl

---

packages/appsync-api/src/cli.ts
packages/appsync-api/src/createApiTemplate.ts
packages/appsync-api/src/createAppSyncResolverHandler.ts
packages/appsync-api/tests/unit/apiTemplate.test.ts
packages/appsync-api/tests/unit/apiTemplateComplexSchema.test.ts
packages/cloudformation/src/CloudFormationTemplate.ts

fix: remove enum resolvers

---

packages/aws-appsync-nodejs/package.json
packages/carlin/package.json
packages/cloud-auth/package.json
packages/cloud-roles/package.json
packages/cloudformation/package.json
packages/components/package.json
packages/config/package.json
packages/forms/package.json
packages/forms/src/FormFieldRadio.tsx
packages/forms/tests/unit/FormFieldRadio.test.tsx
packages/forms/tests/unit/FormFieldTextarea.test.tsx
packages/landing-pages/package.json
packages/react-notifications/package.json
packages/ui/package.json
yarn.lock

fix: radio reset checked

---

docs/storybook/package.json
docs/storybook/stories/forms/Form.stories.tsx
docs/storybook/stories/ui/Input.stories.tsx
packages/ui/jest.config.ts
packages/ui/src/components/Input.tsx
packages/ui/tests/unit/Input.test.tsx
yarn.lock

Task 496 rayza atualizar o componente input

---

package.json
packages/appsync-api/src/createApiTemplate.ts
packages/appsync-api/src/createAppSyncResolverHandler.ts
packages/appsync-api/tests/unit/createAppSyncResolverHandler.test.ts
yarn.lock

- Downgrade Turbo because fo https://github.com/vercel/turbo/issues/3918

feat: add headers to context

---

docs/storybook/.storybook/preview.tsx
docs/storybook/package.json
docs/storybook/stories/ui/Badge.stories.tsx
docs/storybook/stories/ui/Checkbox.stories.tsx
packages/aws-appsync-nodejs/package.json
packages/carlin/package.json
packages/cloud-auth/package.json
packages/cloud-roles/package.json
packages/cloudformation/package.json
packages/components/package.json
packages/config/package.json
packages/forms/package.json
packages/landing-pages/package.json
packages/theme/src/themes/Bruttal/BruttalTheme.ts
packages/ui/package.json
packages/ui/src/components/Badge.tsx
packages/ui/src/index.ts
packages/ui/tests/unit/index.test.tsx
yarn.lock

Task 653 pedro arantes export bagde on ttoss

---

packages/theme/src/themes/Bruttal/BruttalTheme.ts
yarn.lock

feat: add root styles

---

packages/aws-appsync-nodejs/package.json
packages/carlin/package.json
packages/cloud-auth/package.json
packages/cloud-roles/package.json
packages/cloudformation/package.json
packages/components/package.json
packages/config/package.json
packages/forms/package.json
packages/landing-pages/package.json
packages/monorepo/package.json
packages/ui/package.json
packages/ui/src/components/Button.tsx
packages/ui/tests/unit/Button.test.tsx
packages/ui/tests/unit/Input.test.tsx
yarn.lock

fix: add type button as default

---

docs/storybook/stories/ui/Input.stories.tsx
packages/theme/src/themes/Bruttal/BruttalTheme.ts
packages/ui/src/components/Input.tsx

Task 667 rayza modules   update input component

---

packages/ui/src/components/Badge.tsx

fix: removed required icon property

---

docs/storybook/stories/ui/Input.stories.tsx
packages/test-utils/package.json
packages/test-utils/src/assignWindowProperties.ts
packages/test-utils/src/index.ts
packages/theme/src/themes/Bruttal/BruttalTheme.ts
packages/ui/src/components/Input.tsx

Fix input styles with icons

---

docs/storybook/stories/ui/Label.stories.tsx
packages/theme/src/themes/Bruttal/BruttalTheme.ts
packages/ui/src/components/Label.tsx
packages/ui/tests/unit/Label.test.tsx

Task 506 rayza modules   update label

---

docs/storybook/stories/forms/Form.stories.tsx
packages/forms/src/ErrorMessage.tsx
packages/forms/src/FormFieldInput.tsx
packages/forms/tests/unit/FormFieldInput.test.tsx
packages/ui/src/components/Label.tsx

Cu 864ec58t4 rayza modules update form field input

---

docs/storybook/stories/ui/Link.stories.tsx
packages/theme/src/themes/Bruttal/BruttalTheme.ts
packages/ui/src/components/Link.tsx
packages/ui/tests/unit/Link.test.tsx

Task 676 rayza modules create link component

---

docs/storybook/stories/ui/Radio.stories.tsx
packages/theme/src/themes/Bruttal/BruttalTheme.ts

Cu 864ef6ff4 rayza modules   create radio button component

---

docs/storybook/stories/ui/Textarea.stories.tsx
packages/theme/src/themes/Bruttal/BruttalTheme.ts

Task 679 rayza modules update textarea component

---

docs/storybook/stories/forms/Form.stories.tsx
docs/storybook/stories/forms/FormGroup.stories.tsx
docs/storybook/stories/forms/Radio.stories.tsx
docs/storybook/stories/forms/Select.stories.tsx
package.json
packages/forms/src/FormField.tsx
packages/forms/src/FormFieldCheckbox.tsx
packages/forms/src/FormFieldInput.tsx
packages/forms/src/FormFieldRadio.tsx
packages/forms/src/FormFieldSelect.tsx
packages/forms/src/FormFieldTextarea.tsx

Task 682 rayza update form fields

---

packages/carlin/src/deploy/s3.ts
packages/carlin/src/deploy/staticApp/removeOldVersions.ts
packages/carlin/src/deploy/staticApp/staticApp.template.ts
packages/carlin/src/deploy/staticApp/uploadBuiltAppToS3.ts
packages/carlin/tests/unit/staticApp/staticApp.template.test.ts

fix: cloudfront access denied

---

docs/storybook/stories/ui/Badge.stories.tsx
packages/theme/src/themes/Bruttal/BruttalTheme.ts

Task 696 rayza adicionar variant muted ao componente badge

---

docs/website/lifecycle/carlin/index.js
packages/appsync-api/package.json
packages/carlin/package.json
packages/carlin/src/cli.ts
packages/carlin/src/deploy/command.ts
packages/carlin/src/deploy/vercel/command.ts
packages/carlin/src/deploy/vercel/deployVercel.ts
packages/carlin/src/index.ts
packages/carlin/src/utils/exec.ts
packages/carlin/src/utils/index.ts
packages/carlin/src/utils/spawn.ts
packages/carlin/testUtils.ts
packages/carlin/tests/integration/deployVercel.test.ts
pnpm-lock.yaml

Add command `carlin deploy vercel`.

feat: add deploy vercel on carlin

---

packages/layouts/README.md
packages/layouts/src/components/BaseLayout.tsx
packages/layouts/src/components/Layout.tsx
packages/layouts/src/components/StackedLayout.tsx

fix: remove stacked layout from layout

---

packages/carlin/package.json
packages/react-notifications/src/NotificationsModal.tsx
packages/react-notifications/tests/unit/Modal.test.tsx
pnpm-lock.yaml

https://app.clickup.com/t/30901592/TASK-1032

feat: added a button to close react notifications modal

---

packages/graphql-api/README.md
packages/graphql-api/src/cli.ts

feat: add --directory option for schemaComposer.ts

---

packages/appsync-api/src/createApiTemplate.ts
packages/appsync-api/src/createAppSyncResolverHandler.ts
packages/appsync-api/tests/schemaComposer.ts
packages/appsync-api/tests/unit/createAppSyncResolverHandler.test.ts
packages/carlin/src/config.ts
packages/carlin/src/deploy/lambda/buildLambdaSingleFile.ts
packages/graphql-api/README.md

fix: appsync enum substitution

---

packages/cloud-auth/README.md
packages/cloud-auth/src/template.ts
packages/cloud-auth/tests/unit/template.test.ts

feat: principal tag mapping

---

packages/appsync-api/README.md
packages/appsync-api/src/createApiTemplate.ts
packages/appsync-api/tests/unit/apiTemplate.test.ts
terezinha-farm/api/src/cloudformation.ts

feat: add custom domain appsync-api

---

packages/graphql-api-server/src/index.ts

fix: double cors handling

---

packages/eslint-config/config.js

fix: ban React.FC

---

packages/forms/README.md
packages/forms/package.json
packages/forms/src/index.ts
packages/forms/tests/unit/react-hook-form.test.tsx
pnpm-lock.yaml

fix: react-hook-form exports

---

docs/website/carlin.yml
docs/website/docusaurus.config.js

fix: configure spa

---

packages/carlin/jest.config.ts
packages/carlin/package.json
packages/carlin/src/cli.ts
packages/carlin/src/deploy/lambda/deployLambdaLayers.ts
packages/carlin/src/deploy/stackName.spec.ts
packages/carlin/src/deploy/stackName.ts
packages/cloudformation/src/readObjectFile.ts
packages/config/package.json
packages/config/src/babel.ts
pnpm-lock.yaml

fix: remove require from carlin scripts

---

packages/read-config-file/package.json
packages/read-config-file/src/loadConfig.ts
pnpm-lock.yaml

fix: build ts files together

---

docs/storybook/.storybook/main.ts
docs/storybook/package.json
docs/storybook/stories/forms/FormGroup.stories.tsx
packages/forms/README.md
packages/forms/package.json
packages/forms/src/FormGroup.tsx
packages/forms/src/index.ts
packages/forms/tests/unit/FormGroup.test.tsx
packages/forms/tests/unit/MultistepForm.test.tsx
packages/forms/tests/unit/index.test.ts
pnpm-lock.yaml

feat: add name to fo FormGroup

---

docs/website/docs/carlin/03-commands/deploy.mdx
docs/website/plugins/carlin/README.md
docs/website/plugins/carlin/index.mjs
packages/carlin/src/deploy/cloudformation.core.ts
packages/carlin/src/deploy/config.ts
packages/carlin/tests/unit/deploy/cloudformation.core.test.ts
packages/carlin/tests/unit/deploy/stackName.spec.ts
packages/carlin/tests/unit/deploy/utils.spec.ts

feat: saves latest-deploy.json carlin

---

packages/google-maps/src/GoogleMapsProvider.tsx
packages/google-maps/tests/unit/tests/GoogleMapsProvider.test.tsx

fix: google maps loading async

---

docs/website/carlin.yml

fix: issue 610
